name: com.example.flutter_cubit_app
description: A simple Flutter application demonstrating the Cubit pattern for state management. The app features a single screen with a text that toggles between 'Cat' and 'Dog' when clicked, along with corresponding icons.
version: 1.0.0
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  mocktail: ^0.2.0

flutter:
  uses-material-design: true